// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '8.5.1' apply false
    id 'com.android.library' version '8.5.1' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven { 
            url 'https://jitpack.io'
            content {
                includeGroup "com.github.partneroneti"
            }
        }
        maven { 
            url "https://maven-sdk.unico.run/sdk-mobile"
            content {
                includeGroup "io.unico"
                includeGroup "io.unico.liveness"
                includeGroup "io.unico.fingerprint"
                includeGroup "com.acesso.acessobio_android"
            }
        }
    }
}
